// import './js/header';
import './js/header_burger';
// import './js/header_backdrop';
import './js/hero';
import './js/drinkifyapi';
import './js/keyboard';
import './js/alphabetMenu';
import './js/pagination';
import './js/search';
// import './js/favorite-ingredients';
import './js/popupcocktails';
import './js/scroll-up';
import './js/footer';
import './js/scroll-dawn';
import './js/favorite_btn';
