import './js/header';
import './js/hero';
import './js/drinkifyapi';
import './js/keyboard';
import './js/alphabetMenu';
import './js/pagination';
import './js/search';
import './js/favorite-ingredients';
import './js/popupcocktails';
